/*
 * CoolDB: Embedded Database for Java
 *
 * Copyright 2021 Ken Westlund
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cooldb.api;

/**
 * <code>Sequence</code> is a database-wide shared resource that can be used
 * to produce numbers that are guaranteed to be unique in the database.
 * <p>
 * A named <code>Sequence</code> can be created and obtained through a
 * {@link Session}.
 * <p>
 * Despite the name <i>Sequence</i>, the numbers generated by a
 * <code>Sequence</code> are not necessarily consecutive.
 */

public interface Sequence {
    /**
     * Returns the unique name for this Sequence.
     *
     * @return the unique name for this Sequence.
     * @throws DatabaseException if the method fails
     */
    String getName() throws DatabaseException;

    /**
     * Returns the next sequence number. The returned number is guaranteed to be
     * unique and greater than all numbers previously returned by the sequence,
     * but not necessarily consecutive, up to the maximum value for a signed
     * long integer.
     *
     * @return the next sequence number
     * @throws DatabaseException if the method fails
     */
    long next() throws DatabaseException;
}
